name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all      
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        platforms: linux/arm64,linux/amd64
        file: ./Dockerfile
        tags: |
          registry.secitec.net/secretgenerator-go:${{github.run_id}}
          